### ISSUE TITLE
Add script to convert JIM-based ROI file into NIfTI

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_sci#1]
@charleygros can you please add a link to this script? thanks!

**Comment by charleygros** [comment]
@jcohenadad : Sure, I'm happy to help with that if I can. Would you be able to help me with some background information? Not sure what we are looking for here. Cheers

**Comment by jcohenadad** [comment]
@dpfyffer did the ground truth lesion segmentations using JIM. The outputs are .roi files. So we need to convert these .roi files into NIfTI files. IIRC @charleygros a few years ago you compared JIM and deepseg segmentations, and for that purpose you developed a script to convert JIM's roi files into NIfTI.

**Comment by charleygros** [comment]
Thanks for the background info @jcohenadad!

I first had a look in the SCT repo', here some code lines that may be useful to convert a Nifti to ROI: [here](https://github.com/neuropoly/spinalcordtoolbox/blob/master/spinalcordtoolbox/centerline/optic.py#L18).
Related PRs: [PR1377 ](https://github.com/neuropoly/spinalcordtoolbox/pull/1377) and [PR1344](https://github.com/neuropoly/spinalcordtoolbox/pull/1344).

Sadly this is not what you asked (ie ROI --> Nifti): I will dive into old scripts when I get to work today and follow-up on this.

And yes, if @dpfyffer could share a `.roi` file, that would be fantastic and really appreciated.

**Comment by jcohenadad** [comment]
I just sent an email to the developer of JIM (Mark Horsfield), let's see if he has an easier solution.

**Comment by charleygros** [comment]
> I just sent an email to the developer of JIM (Mark Horsfield), let's see if he has an easier solution.

As far as I remember, "ROI --> Nifti" was not too much of an issue, and maybe straightforward with `sct_convert`. Happy to try with @dpfyffer file.

**Comment by dpfyffer** [comment]
> @dpfyffer did the ground truth lesion segmentations using JIM. The outputs are .roi files. So we need to convert these .roi files into NIfTI files. IIRC @charleygros a few years ago you compared JIM and deepseg segmentations, and for that purpose you developed a script to convert JIM's roi files into NIfTI.
> 
> To help us with the task, @dpfyffer could you please upload an .roi file here, along with a NIfTI file associated with the segmentation (upload as a ZIP package).

Thank you @jcohenadad and @charleygros for the updates.
I am more than happy to send you an example file. Let me just anonymize it before I'll upload.

Also, by the end of the week you should have a first BIDSified batch of NIfTI's with corresponding lesion segmentation ROI's.

**Comment by dpfyffer** [comment]
Dear both, please find attached the ZIP containing the NIfTI file with the associated ROI file.
Please let me know if you need anything else or if something is not working.

[1.zip](https://github.com/sct-pipeline/sci-lesion-segmentation/files/6390597/1.zip)

**Comment by jcohenadad** [comment]
Answer from Mark Horsfield:
> Jim has a tool to do this (Masker). It takes an image and an ROI file,
and uses the ROIs to mask out those parts of the image outside (or
inside) the ROIs, creating a new image as output.
http://www.xinapse.com/Manual/
Chapter 13. Particle analysis and masking
Section 7. Masking images

@dpfyffer could you please try this on your end? Thanks

**Comment by dpfyffer** [comment]
Thank you for the update @jcohenadad 
This works very well and is quite simple to do.

Please find attached an updated .zip folder containing
1) the original NIfTI file,
2) the ROI file, and
3) the masked NIfTI file (basically only the lesion), created using soft masking

Is this the way you want me to process all the files we are going to send you over?

[1_masked.zip](https://github.com/sct-pipeline/sci-lesion-segmentation/files/6392600/1_masked.zip)

**Comment by jcohenadad** [comment]
@dpfyffer i think you used the actual image to get the soft mask. Consequently the mask is not weighted correctly:
![image](https://user-images.githubusercontent.com/2482071/116464447-fca1da80-a839-11eb-8ada-fad7b9784c97.png)

What you need to do is get all ones in your image, and _then_ export the soft mask, as explained in https://github.com/sct-pipeline/sci-lesion-segmentation/issues/1#issuecomment-828452351.

One way to have your image with all ones is to do:
~~~
sct_maths -i 1.nii -mul 0 -o 1_all1.nii
sct_maths -i 1_all1.nii -add 1 -o 1_all1.nii
~~~

**Comment by dpfyffer** [comment]
Thanks for clarification @jcohenadad, I gave it another try.
I hope I understood correctly, please find attached the new zip file.

Please let me know if this is what you had in mind.
[1_all1_masked.zip](https://github.com/sct-pipeline/sci-lesion-segmentation/files/6397496/1_all1_masked.zip)

**Comment by jcohenadad** [comment]
Yes, this is perfect! as you can see partial volume is encoded at the periphery of the lesion:
![image](https://user-images.githubusercontent.com/2482071/116564760-44c10b80-a8d3-11eb-9c99-eed5e889e21a.png)

if you can please process all data like that, it would be awesome-- but before doing so, please send us 1-2 subjects that are organized as BIDS so we can validate with you that everything is OK before you do 150 subjects-- thanks!!

**Comment by dpfyffer** [comment]
Nice, good to hear!
I'll do so; you will get that first data tomorrow.

**Comment by dpfyffer** [comment]
Hi both,
I prepared a zip folder with 3 examples organized as BIDS.
(However, I just noticed that it only allows me to attach files of max 10 MB here, and the zip folder has 40 MB.
How would you like me to share the data with you in this case?)

In addition to the midsagittal lesion segmentation, I also segmented the lesion parasagittally for these subjects.
You will see all segmentations in the respective NIfTI files in the 'derivatives' folder.

Please let me know if there needs to be anything added or changed.
For now, I'll send you a zip folder with one subject.

[dataset1.zip](https://github.com/sct-pipeline/sci-lesion-segmentation/files/6406247/dataset1.zip)

**Comment by jcohenadad** [comment]
Hi @dpfyffer,

it looks great! few comments:
- all data need to be in nii.gz (not nii)
- use a site name that is specific to your site (not UBC, which means University of British Columbia). Eg you could go with "zurich"
- to share big data, instead of uploading on GH you could share via a google drive folder or dropbox

**Comment by dpfyffer** [comment]
Okay perfect, let me re-arrange then.
Also, thanks for clarifying what UBC means @jcohenadad  👍 

I'll share with you the data of some more subjects asap!

**Comment by dpfyffer** [comment]
Hi @jcohenadad 
I've uploaded the data of 3 subjects in a zip folder here:
https://drive.google.com/drive/folders/1QmIsQzVLFVGPlK-o1c8LJcw8U8_fxfol?usp=sharing

Please le me know if it looks good like this

**Comment by jcohenadad** [comment]
@dpfyffer The data are excellent, great job!
Could you please also add a JSON file alongside the segmentation? This will be useful in the futur, when we will have different expert raters creating manual labels (eg: compute inter-rater variability, etc.). Here is the convention for the file:

Name: same as the segmentation, but with .json extension. Example: **sub-zh01_ses-01_acq-sag_T2w_lesion-manual.json**

Content:
~~~
{
    "Author": "Bob Dylan",
    "Date": "2020-07-29 21:25:37"
} 
~~~

Note: the field "Date" is optional.

**Comment by jcohenadad** [comment]
@dpfyffer the latest uploaded dataset looks perfect!

**Comment by jcohenadad** [comment]
Thank you @dpfyffer, for the sake of internal record, the dataset is under our internal git-annex secure server under the name `sci-zurich`.
