### ISSUE TITLE
Rethink patch size during training due to subjects with extremely small lesions

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/model_seg_sci#12]
A few subjects have very small lesions compared to the whole input volume. Two examples are shown below. Currently, in the config file `length_3D=[384, 96, 32]` with an overlap of 50% after resampling it anisotropically to `[1, 1, 2]`. Since some information is lost by resampling to a larger voxel size compared to the original, the issue is whether such a large patch size (`length_3D`) is even beneficial during training. 
![sub-zh21_ses-02_overlay](https://user-images.githubusercontent.com/53445351/151424842-8a20e333-8bb4-4a66-ad4c-b8d77e3d2eb3.PNG) | ![sub-zh19_ses-01](https://user-images.githubusercontent.com/53445351/151424855-c5c124fc-b481-4b45-b6f1-aff429226776.PNG)

To Do:
* Consider smaller `length_3D` and `stride_3D` parameters to see if the test metrics improve.

**Comment by naga-karthik** [comment]
Are you suggesting that we should do a trilinear interpolation within the SCT preprocessing itself? I am asking this because:
1. `ivadomed` does not have an option for specifying interpolation during resampling
2. I already am specifying the softseg parameters in the config file for training. However, the resampling transformation that is being applied via the config file uses `scipy.ndimage.zoom` which only does a spline interpolation.

Please let me know if I am missing something!

**Comment by jcohenadad** [comment]
> Are you suggesting that we should do a trilinear interpolation within the SCT preprocessing itself? 

I should have asked to clarify what you meant by 'resampling' (ie which step are you talking about). I thought you were describing the preprocessing pipeline-- if you were, then trilinear interp should be used because as you know the GT is soft. 

> ivadomed does not have an option for specifying interpolation during resampling

then we could add that option 😊 

> I already am specifying the softseg parameters in the config file for training. However, the resampling transformation that is being applied via the config file uses scipy.ndimage.zoom which only does a spline interpolation.

you can specify whatever you want, see the [doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.zoom.html#scipy.ndimage.zoom)

**Comment by naga-karthik** [comment]
> I thought you were describing the preprocessing pipeline-- if you were, then trilinear interp should be used because as you know the GT is soft.

No, I was in fact referring to the `"resampling"` key under `"transformations"` in the config file. But now that you have mentioned that indeed resampling should be done within SCT preprocessing, I am modifying the preprocessing script to add this command. A PR for review should be ready soon! Thank you for the suggestion! :) 

As for specifying the order of interpolation, another parameter should be added for the `"resampling"` transformation in that case. Right now, it only accepts `wspace`, `hspace`, and `dspace`.

**Comment by naga-karthik** [comment]
Update based on a recent discussion with the team - The need to do resampling during SCT preprocessing is not necessary. This is because `ivadomed` already provides [resampling](https://ivadomed.org/configuration_file.html#resample) as a preprocessing step in the config file. Moreover, looking at [this](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/transforms.py#L255) line confirms that `ivadomed` indeed uses trilinear interpolation during resampling (since `order=1`). There are two points regarding this:

1. It should be mentioned under the "resampling" documentation that by default trilinear interpolation is done so that the user is explicitly informed which interpolation method is being used. 
2. In the documentation, "Resample" comes under "transformation" and should also be specified under "transformation" in the config file. This is not intuitive as methods such as `Resample`, `CenterCrop` and `ROICrop` should be categorized under "Preprocessing". 

Regarding points 1 and 2 above, an issue will be opened in ivadomed and fixed accordingly.

**Comment by naga-karthik** [comment]
This issue is no longer relevant as we decided to move to nnUNet for the segmentation model, hence closing
