### ISSUE TITLE
Disappearing lesions across sessions in some subjects?

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/model_seg_sci#14]
In some subjects (i.e. `sub-zh12, sub-zh16, sub-zh22`) that have multiple sessions, it appears that the lesions present in `ses-01` have disappeared in `ses-02`. I am wondering whether something like this is possible? I am aware of the cases where new lesions can develop as time progresses, but I am not sure how to explain the disappearance of a lesion. As far I as understand, a lesion in MS is formed when the myelin sheath at a particular location gets eroded (due to the auto-immune attack). Since scar tissue is already formed, I do not see how this can heal (assuming the time between sessions is not very long) to justify a completely new lesion in the subsequent session.

Below is the example of `sub-zh22`'s `ses-01` and `ses-02` on the left and right, respectively: 

![sub-zh22_ses01](https://user-images.githubusercontent.com/53445351/151962281-e2077221-96a7-4330-9021-0c9cee69cf36.gif) | ![sub-zh22_ses02](https://user-images.githubusercontent.com/53445351/151962315-6bcff431-697b-4458-8618-373610711175.gif)

In `ses-01`, it can be seen that the lesion is near the top of the image, while in `ses-02` a (new) lesion has appeared near the middle (with the previous lesion disappearing).

**Comment by jcohenadad** [comment]
@naga-karthik this is not MS but traumatic SCI

**Comment by naga-karthik** [comment]
Ah okay! Sorry about this confusion! I should have kept this in mind before opening the issue!

**Comment by dpfyffer** [comment]
No need to worry here, the images of the different sessions are just centered differently.
The lesion is located at the exact same position :)

**Comment by naga-karthik** [comment]
Great, thank you for the confirmation!
