### ISSUE TITLE
Method for co-registering axial and sagittal T2w scans 

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/model_seg_sci#16]
This issue aims to open a brief discussion about the type of registration method to be used for co-registering the axial and sagittal T2w scans as a prerequisite before training a multichannel model. 

**Motivation:** Since a single contrast (sagittal T2w) is not enough for a good segmentation, adding targeted contextual information through the axial T2w might be helpful as it would omit the "non-lesion" hyperintense signals. Primarily inspired by [this](https://github.com/ivadomed/model_seg_sci/issues/15#issuecomment-1028174463) comment. Also, another quick note is that the axial T2*w is the ideal scan that could be used for co-registration with sagittal T2w, however, it is not present in the dataset. Therefore, the next immediate option is to co-register axial T2w and the sagittal T2w scans only. 

There are two possible methods for co-registration - (1) A pipeline consisting of ANTs and `sct_register_multimodal` (used in [preprocessing for ms-challenge-2021](https://github.com/ivadomed/ms-challenge-2021/tree/main/preprocessing); see steps 3 and 5) , (2) A DL-based contrast agnostic [multi-modal registration](https://github.com/ivadomed/multimodal-registration) based on Synthmorph (currently being led by @EvanBeal). Any suggestions are welcomed on which method is preferable! 

The goal after co-registration would be to create a multi-channel model, with each channel corresponding to the axial and the sagittal T2w scans (and possibly, the sagittal T1w in the future if the need arises).

**Comment by jcohenadad** [comment]
i'd suggest testing both on a few datasets and then decide between 1 and 2.

**Comment by EvanBeal** [comment]
Some preliminary results have been obtained using the DL-based registration method. 

These results were obtained using the sagittal T2w scans as moving images and register them to the axial T2w scans (fixed images). After a discussion with @naga-karthik, it seems that it could be more interesting to do the opposite and use the sagittal T2w as fixed images as the ground truth is linked to the sagittal T2w scans, suggesting that the radiologists use those scans to label the lesions.  

The two gifs show the registration of the sagittal T2w to the axial T2w for the session 1 of the `sub-zh10`. They are representative of the same results, the only difference being the order that the results are displayed:
![ezgif com-add-text-3](https://user-images.githubusercontent.com/32447627/153779702-35c9877a-5743-4937-aba5-0e5189882052.gif)

![ezgif com-add-text-4](https://user-images.githubusercontent.com/32447627/153779708-839e351a-db05-48cb-9306-37139e1a3a30.gif)

One concern with the use of the DL-based registration method is that currently it includes a preprocessing step to resample the images to an isotropic 1 mm resolution before using them as input of the registration model. This is originally done to ensure to obtain good registration results with the models trained as they have been tested on data that were close to this isotropic 1 mm resolution. However, in this dataset, the actual resolution of the images is around ~0.5 x ~0.5 x ~4. Keeping this preprocessing step could cause some interpolation errors independent to the registration and create some strong blurring that may be difficult to interpret for the model. Therefore, changing the preprocessing of the images could be beneficial but the performance of the registration models is unknown for images with different resolution than the 1 mm isotropic one.

The next steps will be to use the sagittal T2w as fixed images and try different preprocessing to explore the different registration results obtained.

**Comment by jcohenadad** [comment]
> Some preliminary results have been obtained using the DL-based registration method.

Stunning 🤩. Results look very promising!

just a comment: i find it extremely difficult to navigate these animations (and it took me some time to understand these are actually the same-- by "the only difference being the order" I thought you meant that in one case the T2sag is the moving, and on the other case the T2*ax is the moving). Suggestions:
- _not_ display the T2sag in the background when you show the 'ax' image (otherwise it is extremely confusing).
- only show one animation (the 2nd one is unnecessary).

> After a discussion with @naga-karthik, it seems that it could be more interesting to do the opposite and use the sagittal T2w as fixed images as the ground truth is linked to the sagittal T2w scans, suggesting that the radiologists use those scans to label the lesions.

Good point indeed. On the other hand, the T2sag has more coverage than the T2*ax and we _know_ (as a prior info from the MR tech) that the extra coverage of the T2sag does not include the pathological part to segment, so it _could_ make it easier for the seg DL model to learn. In this case, it is trivial to simply apply the transformation to the GT as well (with trilinear interpolation). 

That being said, the model might also be able to learn where the pathology is, given that the T2*ax scan is 'zeroed' everywhere outside of this pathological region (in the superior-inferior direction). Maybe both scenarios should be tried.

**Comment by EvanBeal** [comment]
> just a comment: i find it extremely difficult to navigate these animations (and it took me some time to understand these are actually the same-- by "the only difference being the order" I thought you meant that in one case the T2sag is the moving, and on the other case the T2*ax is the moving). Suggestions:
> - not display the T2sag in the background when you show the 'ax' image (otherwise it is extremely confusing).
> - only show one animation (the 2nd one is unnecessary).

Yes I understand and these are good suggestions thank you ! I didn't know how to present these results so I tried these two approaches but I agree that they are not really convincing. I will follow your suggestions for the coming results 👌

> Good point indeed. On the other hand, the T2sag has more coverage than the T2*ax and we know (as a prior info from the MR tech) that the extra coverage of the T2sag does not include the pathological part to segment, so it could make it easier for the seg DL model to learn. In this case, it is trivial to simply apply the transformation to the GT as well (with trilinear interpolation).

Alright very interesting !

**Comment by EvanBeal** [comment]
New registration results have been obtained with the [DL-based registration method](https://github.com/ivadomed/multimodal-registration) using the sagittal T2w scans as fixed images and the axial T2w scans as moving images.

These results were obtained using the ["two steps" approach](https://github.com/ivadomed/multimodal-registration#registration--evaluation-pipeline-for-large-displacements-two-steps-approach). Before registration, both the moving and fixed images have been resampled to an isotropic 1 mm resolution and the voxel values were scaled between 0 and 1 as preprocessing steps. For each pair of images, the warping field outputted by the registration model has been used with `sct_apply_transfo` to transform the moving volume and register it to the fixed one.

The registration has been done on the whole dataset and here are shown some results that should be representative of the dataset as examples from the different type of lesions observed in the dataset have been selected (following the categorization done by @naga-karthik in [this presentation](https://docs.google.com/presentation/d/1h1mUxVaMYBE09LRlzBeVnff1zlhAQWW-fzy-Id2XMXc/edit#slide=id.g1128e59b305_0_15))

For each subject shown, the sagittal T2w scan and the axial T2w scan are displayed before registration (on top) and after registration (below).

Example of registration for subjects with "easy" (well-defined, circular-ish, dense) lesions:

 <details>
  <summary>sub-zh01_ses-01</summary>

![zh01_before](https://user-images.githubusercontent.com/32447627/154139616-bcac739e-1733-4bb4-b7a7-e7847c70bdcd.gif)
![zh01_after](https://user-images.githubusercontent.com/32447627/154139613-8fef34a0-9419-417a-b80a-f973dac29bc3.gif)
</details>

 <details>
  <summary>sub-zh02_ses-01</summary>

![zh02_before](https://user-images.githubusercontent.com/32447627/154139660-6ab937b1-d166-4ac0-be6e-48b89b3128b5.gif)
![zh02_after](https://user-images.githubusercontent.com/32447627/154139657-685d1045-4439-427e-a24c-4e66cb85548f.gif)
</details>

Example of registration for subjects with large/diffuse lesions:

 <details>
  <summary>sub-zh10_ses-01</summary>

![zh10_before](https://user-images.githubusercontent.com/32447627/154139718-55191fd7-6d16-4c95-81b7-1726c0f64d71.gif)
![zh10_after](https://user-images.githubusercontent.com/32447627/154139717-d87b0e86-a64b-4ca3-84b4-fb403e87ce2b.gif)
</details>

 <details>
  <summary>sub-zh21_ses-01</summary>

![zh21_before](https://user-images.githubusercontent.com/32447627/154138807-5ddd0b22-48b2-475d-af42-d935a7039666.gif)
![zh21_after](https://user-images.githubusercontent.com/32447627/154138804-cf4cdcec-34a3-4a93-b1fc-cef87172ab85.gif)
</details>

Example of registration for subjects with less hyper-tense signals:

 <details>
  <summary>sub-zh16_ses-01</summary>

![zh16_before](https://user-images.githubusercontent.com/32447627/154139003-b55977a1-f0a5-4a5e-b8fc-326c984fa0de.gif)
![zh16_after](https://user-images.githubusercontent.com/32447627/154139002-84a2627e-18c6-4ba2-90f8-8229691b49b7.gif)
</details>

 <details>
  <summary>sub-zh17_ses-01</summary>

![zh17_before](https://user-images.githubusercontent.com/32447627/154139049-81c1550c-e0f1-4626-a1c2-f9e970ca58fa.gif)
![zh17_after](https://user-images.githubusercontent.com/32447627/154139047-52fca8c2-8b89-4c57-95f1-c74c50ce71dd.gif)
</details>

Example of registration for subjects with dot-sized lesions:

 <details>
  <summary>sub-zh12_ses-01</summary>

![zh12_before](https://user-images.githubusercontent.com/32447627/154139172-a71d0965-ba6c-4490-9cc0-b2ab86669c70.gif)
![zh12_after](https://user-images.githubusercontent.com/32447627/154139169-d6893b05-f108-4dcb-9db9-cf3e893ea64a.gif)
</details>

 <details>
  <summary>sub-zh15_ses-01</summary>

![zh15_before](https://user-images.githubusercontent.com/32447627/154139204-6f388b16-c8a0-4144-b3ea-7045924d541d.gif)
![zh15_after](https://user-images.githubusercontent.com/32447627/154139202-55d6e646-5cd1-49c5-8454-a69e42d17474.gif)
</details>

**Comment by EvanBeal** [comment]
## Registration results - axial fixed & sagittal moving

Registration results for the [DL-based registration method](https://github.com/ivadomed/multimodal-registration) using this time **the axial T2w scans as fixed images and the sagittal T2w scans as moving images**.

Again, the results were obtained using the ["two steps" approach](https://github.com/ivadomed/multimodal-registration#registration--evaluation-pipeline-for-large-displacements-two-steps-approach). Before registration, both the moving and fixed images have been resampled to an isotropic 1 mm resolution and the voxel values were scaled between 0 and 1 as preprocessing steps. For each pair of images, the warping field outputted by the registration model has been used with `sct_apply_transfo` to transform the moving volume and register it to the fixed one.

For each subject shown, the axial T2w scan and the sagittal T2w scan are displayed before registration (on top) and after registration (below).

Example of registration for subjects with "easy" (well-defined, circular-ish, dense) lesions:

 <details>
  <summary>sub-zh01_ses-01</summary>

![sub-zh01_before](https://user-images.githubusercontent.com/32447627/154151982-cc393127-d5ad-4280-98dd-82504392f65c.gif)
![sub-zh01_after](https://user-images.githubusercontent.com/32447627/154151978-86c5c84d-2e20-421d-8a34-655db3b57199.gif)
</details>

 <details>
  <summary>sub-zh02_ses-01</summary>

![sub-zh02_before](https://user-images.githubusercontent.com/32447627/154152052-04ad8a79-47b1-4f76-bdb5-6c2b35c07b2d.gif)
![sub-zh02_after](https://user-images.githubusercontent.com/32447627/154152050-79edf124-d911-446f-8748-b84405cb8933.gif)
</details>

Example of registration for subjects with large/diffuse lesions:

 <details>
  <summary>sub-zh10_ses-01</summary>

![sub-zh10_before](https://user-images.githubusercontent.com/32447627/154152241-b2221946-6aa0-4692-b10c-dbda6433ad37.gif)
![sub-zh10_after](https://user-images.githubusercontent.com/32447627/154152239-3b1dff5d-3323-4dde-ab79-d0eade6d6790.gif)
</details>

 <details>
  <summary>sub-zh21_ses-01</summary>

![sub-zh21_before](https://user-images.githubusercontent.com/32447627/154152293-673f02ad-9d90-40e9-b974-bd2a7d5172f4.gif)
![sub-zh21_after](https://user-images.githubusercontent.com/32447627/154152290-d22d206c-d57b-4bcd-8972-cf5cc4910a04.gif)
</details>

Example of registration for subjects with less hyper-tense signals:

 <details>
  <summary>sub-zh16_ses-01</summary>

![sub-zh16_before](https://user-images.githubusercontent.com/32447627/154152331-0a9c0321-8db1-4e0f-8fc9-e720b1736208.gif)
![sub-zh16_after](https://user-images.githubusercontent.com/32447627/154152330-f387641e-0d9f-4a4e-b17c-560b50377172.gif)
</details>

 <details>
  <summary>sub-zh17_ses-01</summary>

![sub-zh17_before](https://user-images.githubusercontent.com/32447627/154152397-8aaf5d8a-4d40-45c9-b389-61d81cce2dc5.gif)
![sub-zh17_after](https://user-images.githubusercontent.com/32447627/154152393-0b7174c2-db1f-432d-90fe-dae2ddd2f29a.gif)
</details>

Example of registration for subjects with dot-sized lesions:

 <details>
  <summary>sub-zh12_ses-01</summary>

![sub-zh12_before](https://user-images.githubusercontent.com/32447627/154152453-008aa610-b3b5-41a2-8a4b-bf3b93509933.gif)
![sub-zh12_after](https://user-images.githubusercontent.com/32447627/154152448-dd63b44e-2cef-4c1b-89e2-f59dec11b99e.gif)
</details>

 <details>
  <summary>sub-zh15_ses-01</summary>

![sub-zh15_before](https://user-images.githubusercontent.com/32447627/154152489-6a97e648-89e0-420a-99f6-3e8077633c1e.gif)
![sub-zh15_after](https://user-images.githubusercontent.com/32447627/154152487-20537134-c026-45dc-80ea-64cd3f2eaa5a.gif)
</details>

**Comment by jcohenadad** [comment]
Some feedback. Regarding the "sagittal fixed & axial moving" scenario (https://github.com/ivadomed/model_seg_sci/issues/16#issuecomment-1040740731), there is a major issue, which is that the deformation has too many degrees of freedom and actually deform the internal structure of the spinal cord. Example for `sub-zh01_ses-01`:
before reg: 
![Screen Shot 2022-02-15 at 8 48 34 PM](https://user-images.githubusercontent.com/2482071/154180894-c66f0b05-0fee-4357-96dd-b9de7538758c.png)

After reg:
![Screen Shot 2022-02-15 at 8 48 39 PM](https://user-images.githubusercontent.com/2482071/154180901-3c4336a0-9452-4fee-8d7a-bbdefbdf1718.png)

Notice the shape of the lesion is slightly expanded in the 'reg' case. This is highly problematic, as it spuriously changes the characteristics of the pathology. This is definitely something we should avoid, at all cost. 

The bottomline is that the two images have very different contrast properties, and the image information content is ill-defined along the SI direction (for the axial image) and along the RL direction (for the sagittal image). This 'lost' information generates weird and unpredictable behaviours for this registration method. 

I would personally stay away from this DL-based registration in the context of this project, and instead use deformation methods with much lower degree of freedom (eg: slicereg, which are simple XY translations (ie no in-plane deformation) regularized along the SI axis).

**Comment by naga-karthik** [comment]
Following the discussion above, here are a few preliminary results using `sct_register_multimodal`. A few important points - (i) before registering both the axial and sagittal images have been isotropically resampled to 1mm x 1mm x 1mm resolution, and (ii) a draft PR #17 has also been created for detailed information on which commands have been used and how the registration is done. Note that currently, the SC segmentation masks have also been used as the input for `sct_register_multimodal`. 

<details>

<summary> sub-zh02-ses01 </summary>

![sub-zh02_ses-01_reg_annotated](https://user-images.githubusercontent.com/53445351/154368240-aa996f7b-53bf-4a45-b3fb-a68855657b00.gif)

</details>

<details>

<summary> sub-zh06-ses01 </summary>

![sub-zh06_ses-01_reg_annotated](https://user-images.githubusercontent.com/53445351/154368511-660f1f24-ad65-4131-ba23-2fdf1a091fc4.gif)


</details>

<details>

<summary> sub-zh11-ses01 </summary>

![sub-zh11_ses-01_reg_annoated](https://user-images.githubusercontent.com/53445351/154368518-b740b5f6-1ddb-43ba-9bad-058ca08713c8.gif)

</details>


<details>

<summary> sub-zh14-ses01 </summary>

![sub-zh14_ses-01_reg_annoted](https://user-images.githubusercontent.com/53445351/154368652-ea234eb8-56f9-4662-9963-61155976aa6e.gif)

</details>

Interpretation: I think that the registration has worked satisfactorily - there is a slight gap between the sagittal and the axial image (as if the axial image is slightly shifted when overlayed on top of the sagittal image), which is corrected after the registration.

**Comment by jcohenadad** [comment]
> a draft PR https://github.com/ivadomed/model_seg_sci/pull/17 has also been created for detailed information on which commands have been used

@naga-karthik a PR evolves (ie: multiple commits in one PR). Could you please instead link the commit hashtag that was used to generate these results?

**Comment by jcohenadad** [comment]
@naga-karthik nice preliminary results. However be aware that the comparison in https://github.com/ivadomed/model_seg_sci/issues/16#issuecomment-1042376787 is misleading, because you are comparing registered axial images (which are 1mm iso) with non-registered axial images (which are non-isotropic). When images with different resolution are displayed on FSLeyes, there is a 'streaking' effect (we discussed it in one of our meeting), which gives the impression that there is a slight shift between the two overlaid images. This biased the visual assessment of registration quality. What you want to compare is the non-registered and the registered in the _same_ space (ie: bring the non-registered image in the space of the destination image-- see https://github.com/ivadomed/model_seg_sci/pull/17/files#r808605182)

**Comment by naga-karthik** [comment]
Thank you for the suggestions @jcohenadad! I have made some changes to the preprocessing pipeline (see file version 92c57b5ff4265a85ab86803b7e91faf0456cc3f2) and below is the comparison of the registration results. This time I have used the same subset as in @EvanBeal's [comment](https://github.com/ivadomed/model_seg_sci/issues/16#issuecomment-1040740731) above, so a direct comparison between DL-based and SCT-based methods is now possible.

**How to interpret the gifs**: First, the resampled sagittal T2w is seen, then the axial T2w is overlayed on the sagittal, and finally the registered axial T2w is shown. Notice a slight shift the registered axial T2w. Also, note that all images are ensured to lie in the same discrete space.

<details>

<summary> sub-zh02_ses-01 </summary>

![sub-zh02_annotated](https://user-images.githubusercontent.com/53445351/154617443-d8b576c9-3fab-4cb1-8e61-8b1dfb1322fd.gif)

</details>

---

<details>

<summary> sub-zh10_ses-01 </summary>

![sub-zh10_annot](https://user-images.githubusercontent.com/53445351/154617458-9f9eb643-fb2f-4e49-88e8-8689a4ad8ff2.gif)

</details>

---

<details>

<summary> sub-zh12_ses-01 </summary>

![sub-zh12_annot](https://user-images.githubusercontent.com/53445351/154617473-60382524-c25c-4d7a-99d2-8b30d884e596.gif)

</details>

---

<details>

<summary> sub-zh16_ses-01 </summary>

![sub-zh16_annot](https://user-images.githubusercontent.com/53445351/154617488-b281e191-7735-408f-b00b-a50d72d3196b.gif)

</details>

---

My bottomline: It appears that in cases the registration has indeed resulted in minor deformation - very minor in case of `sub-zh12`, `sub-zh02` and relatively noticeable in `sub-zh10`, `sub-zh16`. Also, currently, the following params are being used by `sct_register_multimodal` - `step=1`, `type=seg`, `algo=slicereg` , `metric=MeanSquares`, `smooth=3`. I am curious as to how the `metric=CC` will work since it is mentioned in the docs that it can be used for images with same contrast.

**Comment by jcohenadad** [comment]
looks promising! i've added a few comments:
- https://github.com/ivadomed/model_seg_sci/commit/92c57b5ff4265a85ab86803b7e91faf0456cc3f2#r66991263
- https://github.com/ivadomed/model_seg_sci/commit/92c57b5ff4265a85ab86803b7e91faf0456cc3f2#r66991407

**Comment by naga-karthik** [comment]
So I have made some changes based on the comments and shown below are the results. The how-to of interpreting them remains the same as in the previous comment. Here are the main changes: 

1. I felt that the isotropic 1mm x 1mm x 1mm was making it too blurry in the sagittal T2w and the axial T2w (where the native resolution is ~0.5 mm x ~0.5mm, hence I modified the resampling factor as isotropic 0.75 mm x 0.75 mm x 0.75 mm. The images are relatively better in terms of visualization
2. Following [this](https://github.com/ivadomed/model_seg_sci/pull/17#commitcomment-66991407) suggestion - the registration has now been done _after_ cropping. An immediate benefit of this was that the registration deformation could be easily seen without having to zoom in/out too much.

<details>

<summary> sub-zh01_ses-01 </summary>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/53445351/154761890-8d1fd182-6dad-434a-8487-db1a3cdf7bbb.gif)

</details>

<details>

<summary> sub-zh02_ses-01 </summary>

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/53445351/154761908-7a9d057a-a96f-44ca-8ae6-1b346c171d3f.gif)

</details>

For these subjects, the images as-they-are appear to be nearly registered, so explicitly registering them hasn't shifted much.

---

<details>

<summary> sub-zh10_ses-01 </summary>

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/53445351/154761926-71345382-9314-4f09-9131-347d8fd31171.gif)

</details>

For this subject, I believe that the registration actually worsened it. There is a noticeable shift in the registered ax and the sag image. The original ax and sag images were in fact decently aligned.

---

<details>

<summary> sub-zh16_ses-01 </summary>

![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/53445351/154761932-6472f2c4-91f5-4d31-89e3-4094f1d0697a.gif)

</details>

For this subject, we can see that the registration helped. The overlap between the registered ax and the sag images is almost full indicating a good registration.

---

Final thoughts: It has been difficult to understand whether the registration was good or bad - in some cases, the deformation is pretty small because the images were already well-aligned, and in others, there is a noticeable shift. However, in my opinion, the current results are not satisfactory (to me) and I am wondering whether tweaking the registration parameters a bit more might (or might not) improve the results.

**Comment by jcohenadad** [comment]
> Final thoughts: It has been difficult to understand whether the registration was good or bad - in some cases, the deformation is pretty small because the images were already well-aligned, and in others, there is a noticeable shift. However, in my opinion, the current results are not satisfactory (to me) and I am wondering whether tweaking the registration parameters a bit more might (or might not) improve the results.

Indeed, tweaking registration parameters might improve the results. A useful approach is to look at the subjects where registration didn't work (eg `sub-zh10_ses-01`) and understand _why_ it didn't work. Start looking at the segmentation: is it accurate in both the axial and sagittal image? Then check the result of the registered segmentation (you could look at the temporary files from `sct_register_multimodal` with the flag `-r 0`, it is quite insightful). We could also have a 30min meeting where we can look at it.

**Comment by jcohenadad** [comment]
I'd suggest doing the registration based on the image. Here is an example syntax:
~~~
sct_register_multimodal -i sub-zh16_ses-01_acq-ax_T2w.nii.gz -d sub-zh16_ses-01_acq-sag_T2w_r_crop.nii.gz -m sub-zh16_ses-01_acq-sag_T2w_r_seg_dil.nii.gz -param step=1,type=im,metric=CC,algo=slicereg,iter=30,poly=2,smooth=0 -qc qc -dseg sub-zh16_ses-01_acq-sag_T2w_r_seg.nii.gz -r 0
~~~

note: we need the `-dseg` only for the QC report (but you need the sag-T2w segmentation anyway for the cropping)

**Comment by jcohenadad** [comment]
You could also add a step when you rigid-register the volume:

~~~
sct_register_multimodal -i sub-zh16_ses-01_acq-ax_T2w.nii.gz -d sub-zh16_ses-01_acq-sag_T2w_r_crop.nii.gz -param step=1,type=im,algo=rigid,deformation=1x1x1,iter=30,smooth=0:step=2,type=im,metric=CC,algo=slicereg,iter=30,poly=5,smooth=0 -qc qc -dseg sub-zh16_ses-01_acq-sag_T2w_r_seg.nii.gz -r 0
~~~

although this is not recommended given the thick axial sliced (interpolation errors)

**Comment by naga-karthik** [comment]
I am observing some noticeable differences w.r.t on comparing the segmentation-based and image-based (following [this](https://github.com/ivadomed/model_seg_sci/issues/16#issuecomment-1047068796) comment but **without** the mask) in terms of the quality of registration. My next question is - When is it better to use the image-based method and when is it better for the seg-based method for SC registration? I am wondering whether we should usually go for image-based registration (7/10 times) because - seg-based reg might not be robust if we depend on segmentation from multiple contrasts (assuming that we don't have GT SC masks), and moreover, it is difficult to get GT SC masks for every time. 

That said, one of the cons of the image-based reg would be that there would no proper constraint on the boundary under consideration ie if the anterior spine is static and the SC itself is relatively shifted (because of its very structure), then image-based reg would not be optimal. Whereas having an SC mask as a reference would help in this case.

Is there anything more that I should be knowing (am I missing something)?

**Comment by jcohenadad** [comment]
> I am observing some noticeable differences w.r.t on comparing the segmentation-based and image-based (following https://github.com/ivadomed/model_seg_sci/issues/16#issuecomment-1047068796 comment but without the mask) in terms of the quality of registration. My next question is - When is it better to use the image-based method and when is it better for the seg-based method for SC registration? I am wondering whether we should usually go for image-based registration (7/10 times) because - seg-based reg might not be robust if we depend on segmentation from multiple contrasts (assuming that we don't have GT SC masks), and moreover, it is difficult to get GT SC masks for every time.

i agree with this analysis. Requiring the segmentation for the axial image is a _big_ constraint (it ads on the QC, manual correction, etc.). So if the image-based is reasonably good, then let's stick to it.

> That said, one of the cons of the image-based reg would be that there would no proper constraint on the boundary under consideration ie if the anterior spine is static and the SC itself is relatively shifted (because of its very structure), then image-based reg would not be optimal. Whereas having an SC mask as a reference would help in this case.

I'm not sure I understand this explanation. Maybe a drawing would help me understand?

**Comment by naga-karthik** [comment]
Sure, it is a bit difficult to exactly show it, but I'll try. Consider the gif below that shows the overlay of the sagittal T2w and axial T2w registered. Observing, in particular, the axial view only (i.e. middle). We can see that the SC has been registered properly, but if we look closely near the Anterior direction, there is still some minute shift between the images. Note that this is definitely better than the un-registered axial T2w image, but, it is _this_ problem that I was talking about above as a "con" in my previous comment. If we instead had an SC mask, this (minor) shift could've been avoided. 

<details>

<summary> sub-zh16_ses01 shift </summary>

![screenshot_sub-zh16](https://user-images.githubusercontent.com/53445351/155246046-5f8885f4-88a7-4af9-94b3-9d86a56e39a5.gif)

</details>

Also, based on [this](https://github.com/ivadomed/model_seg_sci/issues/16#issuecomment-1047068796) comment, I ran the image-based reg pipeline for all subjects (without mask) and the qc report for the same can be found [here](https://drive.google.com/drive/u/0/folders/1Wb9B1wknDtnSPjI4NUCBiYvK1UJEGGBS). I think the registration is mostly good this time, definitely better compared to the segmentation-based registration!

**Comment by jcohenadad** [comment]
i see. Honestly I think this misregistration is minor and you can move forward with the training. Good job registering this dataset, that was a challenging one!

**Comment by naga-karthik** [comment]
Closing this as we're currently only using single contrast `acq-sag_T2w` and want to move away from registration of ax and sag images as a preprocessing step.
