### ISSUE TITLE
Lesion labeling extending outside the axial T2w image

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/model_seg_sci#18]
For one of the subjects `sub-zh21_ses-01` (a possible outlier), the GT lesion segmentation is extending outside the axial T2w image (see figure below). This is concerning because the motivation for registering the axial and sagittal images was based on the assumption that the lesion typically lies within the boundaries of the axial T2w image (more details in [this](https://github.com/ivadomed/model_seg_sci/issues/15#issuecomment-1028174463) comment). Also, this does not appear like a "labeling issue" because the lesion can be seen on closely observing the sag T2w image itself (by tweaking the contrast).

<details>

<summary> sub-zh21_ses-01  </summary>

![Capture](https://user-images.githubusercontent.com/53445351/155177407-0bcbf16d-528c-4822-9742-69e4269011ac.PNG)

</details>

The issue is that if we want the model to be constrained to the axial T2w image, then there is a chance that some part of the lesion can be missed. In my opinion, a trade-off should be made here because - if we don't constrain to the axial image, then there's too much unnecessary info (on a already challenging dataset), AND, if we do constrain, then we might miss out on the lesions. Any other suggestions on this?

**Comment by jcohenadad** [comment]
As a first step, I would go with "consider the axial AND sagittal image only" (ie: forget about the lesion outside the axial view).
