### ISSUE TITLE
Different "direction" attribute error in Zurich data when loading with torchIO

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/model_seg_sci#21]
In order to test a weighted sampling approach in torchIO, I was trying to load data patches and that resulted in an error shown below. 
```
RuntimeError: More than one value for "direction" found in subject images:
{'label': (0.9981166689418295,
           -0.05645437422859611,
           -0.024005560303328167,
           0.05643535204519909,
           0.9984051800899562,
           -0.0013494249498021132,
           0.024045087232130596,
           0.0,
           0.9997109142781367),
 'sag_t2w': (0.9981165875284604,
             -0.05645307696797697,
             -0.024007068248685814,
             0.056436713381733866,
             0.9984052534421318,
             -0.0013574772136438992,
             0.02404527153536297,
             0.0,
             0.9997108671659608)}
```
This is one of the checks that TorchIO performs automatically to check the consistency of the data. For e.g. some of the checks ensure the spacing, orientation and the [gradient direction](https://torchio.readthedocs.io/data/image.html#image) (see 4th paragraph here) are correct. 

To see whether it is an issue with TorchIO, I tried the same data loading procedure with sci-colorado data and it worked without errors. This suggests two things: (1) since both datasets are SCT-preprocessed in the same way, there is no issue with the SCT preprocessing output, and (2) the issue is with sci-zurich data and not on TorchIO's side. 

@jcohenadad Would you have any suggestions as to how we can ensure that the directions for the input image and the label are the same?

**Comment by jcohenadad** [comment]
well to me it just seems like a precision issue, right? 
0.9997109142781367 vs. 0.9997108671659608

so you can simply change the precision threshold

**Comment by naga-karthik** [comment]
Well, I looked into that as well i.e. lowering the threshold tolerance to 1e-2. I still run into this error despite doing that. Looking into it a bit more.
