### ISSUE TITLE
Missing lesion labels for some subjects

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/model_seg_sci#22]
The preprocessing routine resulted in an error for the following subjects: 

<img width="741" alt="Screen Shot 2023-01-06 at 3 39 13 PM" src="https://user-images.githubusercontent.com/53445351/211125820-352c3134-4c8c-479e-8993-aadd475b6640.png">

Upon further inspection, it was found that these subjects do not have the corresponding labels (that is, the `*_lesion-manual.nii.gz` in the `derivatives/labels/` folder. There could be two possibilities here: (a) lesions were not annotated by mistake, or (b) these subjects do not have any lesions. However, on visual inspection, it seems that (b) is more plausible, hence there are no label files for these subjects. 

There are again two ways to work around this:

1. Remove these subjects from the dataset, thus ensuring that the dataset only has subjects with lesions. 
2. Add empty label files for these subjects in the dataset (such that these subjects are not excluded)

Would (2) be a better option to proceed with?

**Comment by jcohenadad** [comment]
> Add empty label files for these subjects in the dataset (such that these subjects are not excluded)

this is the way to go (to make sure your model is exposed with true negatives-- important for specificity)

**Comment by naga-karthik** [comment]
Closing as completed in this [issue](https://github.com/neuropoly/data-management/issues/201).
