### ISSUE TITLE
confusing use of relative and absolute path for variable

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_sci#27]
here, it woudl be better to just define a variable wiht absolyte path, so that if you change folder, the variable will still work

https://github.com/ivadomed/model_seg_sci/blob/f2df15c659cf47908e2d055982c3d87718e3e7be/preprocessing/preprocess_data_sci-zurich.sh#L151

**Comment by kiristern** [comment]
sorry, I don't think I understand. I think this is already an absolute path, which we define since we `cd` to the derivatives folder in `line 137`
