### ISSUE TITLE
`convert_bids_to_nnUNetv2.py` - `{args.dataset_name}` is missing in output filenames

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model_seg_sci#36]
The current version of `convert_bids_to_nnUNetv2.py` script creates filenames without `{args.dataset_name}`:

https://github.com/ivadomed/model_seg_sci/blob/f3dd02c54c62275ef5e935f82a83ef8e39480117/dataset-conversion/convert_bids_to_nnUNetv2.py#L150-L151

`{args.dataset_name}` is required by [compute_test_metrics_anima.py](https://github.com/ivadomed/model_seg_sci/blob/main/utils/compute_test_metrics_anima.py), though.

TODO: include `{args.dataset_name}` into filenames (as was done in one of the previous `convert_bids_to_nnUNetv2.py` versions):

https://github.com/ivadomed/model_seg_sci/blob/d8f464738f5b2e5d309a2c5e1d2af8d47434a44b/dataset-conversion/convert_bids_to_nnUNetv2.py#L122-L123

**Comment by naga-karthik** [comment]
This was an important addition! It has been fixed in da90881b4b95ec174d80e285b70d988238820c7f. The issue can now be closed!
