### ISSUE TITLE
`compute_test_metrics_anima.py` - anima folder name mismatch

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model_seg_sci#37]
The following lines instruct you to create  `.anima` folder:

https://github.com/ivadomed/model_seg_sci/blob/f3dd02c54c62275ef5e935f82a83ef8e39480117/utils/compute_test_metrics_anima.py#L52-L54

However, line 96 then expects `.anima_4.2`:

https://github.com/ivadomed/model_seg_sci/blob/f3dd02c54c62275ef5e935f82a83ef8e39480117/utils/compute_test_metrics_anima.py#L96

**Comment by naga-karthik** [comment]
Thanks for noticing this! This has been updated in 73ecb14d1dd74c874f0279bc55c1aa6571123a57.
