### ISSUE TITLE
Use data augmentation strategy on MS lesions 

### ISSUE THREAD

**Issue by naga-karthik** [ivadomed/model_seg_sci#44]
In a brief discussion with @valosekj, we noticed that the `basel-mp2rage` has both MS patients (about `n=180`) and healthy controls (HC) (about `n=100`). This dataset presents a good way to test the augmentation script by using the healthy controls as test beds for copying lesions for the MS patients. Our hypothesis is that since the augmentation will be done within the dataset (unlike sci-zurich and spine-generic, **but** between MS and HC patients, the intensity issues we have been facing should not be that problematic. 

Steps to test the on the `basel-mp2rage` dataset: 

- [ ] Modify the existing script to work with a single dataset by keeping the BIDS structure
- [ ] Update the conversion script to handle original and augmented (BIDS) data and carefully convert (i.e. without dataset bleeding) to nnUNet
- [ ] Get some coffee and train the model! :)

**Comment by valosekj** [comment]
I believe we can close this issue as not planned
