### ISSUE TITLE
Training a model on `sci-zurich` subjects without metal artifacts

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model_seg_sci#49]
Note: originally posted as https://github.com/ivadomed/model_seg_sci/issues/43#issue-1770424736

---

# Experiment I - subjects without metal artifacts

This issue collects notes about training a model on `sci-zurich` subjects without metal artifacts.

0. We created a lesion QC (saved: `~/duke/projects/ml_sci_seg/qc_zurich_sagittal`) and identified 33 subjects with poor data quality (`~/duke/projects/ml_sci_seg/qc_zurich_sagittal/qc_artifact.yml` and `~/duke/projects/ml_sci_seg/qc_zurich_sagittal/qc_fail.yml`). These YAML lists are used to exclude the subjects during BIDS to nnUNet dataset conversion in the next step.

1. BIDS to nnUNet dataset conversion

Script:
[dataset-conversion/convert_bids_to_nnUNetv2.py](https://github.com/ivadomed/model_seg_sci/blob/main/dataset-conversion/convert_bids_to_nnUNetv2.py)

NOTE: we are working with RPI `sci-zurich`

Command:

```
python convert_bids_to_nnUNetv2.py --path-data ~/extrassd1/janvalosek/data/sci-zurich-rpi --path-out ~/extrassd1/janvalosek/data/sci-zurich-good-subjects-nnunet/ --dataset-name tSCILesionsZurichGoodSubjects --dataset-number 525 --split 0.8 0.2 --seed 99 --good-subjects-only --path-yaml ~/duke/projects/ml_sci_seg/qc_zurich_sagittal/qc_artifact.yml ~/duke/projects/ml_sci_seg/qc_zurich_sagittal/qc_fail.yml
```

2. Copy the dataset to the `${nnUNet_raw}` folder

```
cp -r ~/extrassd1/janvalosek/data/sci-zurich-good-subjects-nnunet/Dataset525_tSCILesionsZurichGoodSubjects ${nnUNet_raw}/
```

3. Validate dataset integrity and run training

```
nnUNetv2_plan_and_preprocess -d 525 --verify_dataset_integrity
```

```
nnUNetv2_train 525 3d_fullres 0
```

TODO: add performance results

**Comment by naga-karthik** [comment]
We decided to not exclude subjects so not continuing with this experiment.
