### ISSUE TITLE
Issue with JSON files for the Zurich dataset

### ISSUE THREAD

**Issue by jcohenadad** [ivadomed/model_seg_sci#5]
The JSON files associated with the Zurich dataset are not BIDS compliant. They seem to have been generated with a Matlab software. Example for **sub-zh01_ses-01_acq-ax_T2w**:
```json
{
	"history": {
		"procstep": {
			"descrip": "dicom to nifti import",
			"version": [
				"matlab 9.7.0.1190202 (R2019b)",
				"spm_dicom_convert.m - SPM12 (7219)"
			],
			"procpar": []
		},
		"input": {
			"filename": "AnonymousFileName",
			"history": []
		},
		"output": {
			"imtype": "ORIGINAL\\PRIMARY\\M\\NORM\\DIS2D ",
			"units": "a.u."
		}
	},
	"acqpar": [
		{
			"FileMetaInformationGroupLength": 192,
			"FileMetaInformationVersion": [0,1],
```

**Comment by naga-karthik** [comment]
I think this should be discussed in the next meeting? This still presents a problem with the standard ivadomed training pipeline. 

For now, a quick-fix workaround for the issue with JSONs has been to remove all the `.json` files from the BIDS dataset and disabling BIDS validator by adding the argument `validate=False` in [this](https://github.com/ivadomed/ivadomed/blob/master/ivadomed/loader/bids_dataframe.py#L110) line in ivadomed's loader. That said, this fix works under the assumption that the JSON metadata will not be used at any time during training the segmentation model.

**Comment by jcohenadad** [comment]
> For now, a quick-fix workaround for the issue with JSONs has been to remove all the .json files from the BIDS dataset and disabling BIDS validator by adding the argument validate=False in this and this line in ivadomed's loader. That said, this fix works under the assumption that the JSON metadata will not be used at any time during training the segmentation model.

this is not the first time nor the last time this will happen, so we need more flexibility towards problematic JSON files, otherwise we will keep doing these hacks (which take time and are error-prone).

**Comment by naga-karthik** [comment]
Closing this as it is not relevant because we moved on from `ivadomed`
