### ISSUE TITLE
Move reorientation to the original orientation to `packaging_utils.py`?

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model_seg_sci#52]
This is just a minor nitpick, but I found it a little confusing that `sct_image -i {} -setorient RPI` is located under [packaging/packaging_utils.py](https://github.com/ivadomed/model_seg_sci/blob/3757fad091f11f1556fe76037e6053826dd6a120/packaging/packaging_utils.py#L72C24-L72C54) but reorientation back to the original orientation is located under the main script [packaging/run_inference.py](https://github.com/ivadomed/model_seg_sci/blob/main/packaging/run_inference.py#L182-L183).

Also, the following comment should be changed
https://github.com/ivadomed/model_seg_sci/blob/3757fad091f11f1556fe76037e6053826dd6a120/packaging/run_inference.py#L182

to:

`reorient the image to the original orientation using SCT `

**Comment by naga-karthik** [comment]
Yeah, I was aware of this while writing it but I included it in the inference script thinking that it's just a few lines, but I agree, it's not following the trend. I will fix it in the next commit

**Comment by naga-karthik** [comment]
Fixed in commits bff26c5fbede22adbfb91389af70a9a682cace3b and a2fe8796cafce65a8e61745acdf3f59804e952da!

**Comment by naga-karthik** [comment]
Closing as it has been fixed!
