### ISSUE TITLE
Comparison of model performance with other methods

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model_seg_sci#54]
### Spinal cord

For the spinal cord segmentation, we can compare our model with:
- [x] `sct_deepseg_sc -kernel 2d` 
- [x] `sct_deepseg_sc -kernel 3d`
- [x] `sct_propseg`
- [x] `contrast_agnostic`

Note: compare performance especially in lumbar regions.

Comparison of our nnUNet model with other methods (`sct_propseg`, `sct_deepseg_sc -kernel 2d`, `sct_deepseg_sc -kernel 3d`) on sci-zurich and sci-colorado datasets is done using the [comparison_with_other_methods.sh](https://github.com/ivadomed/model_seg_sci/blob/442a946c80dabd9a7950da9c0a3babd4dad79128/baselines/comparison_with_other_methods.sh) script. For details, see [baselines/README.md](https://github.com/ivadomed/model_seg_sci/blob/442a946c80dabd9a7950da9c0a3babd4dad79128/baselines/README.md).

### Lesions

For the lesion segmentation, we can compare our model with:
- [ ] `sct_deepseg_lesion` - not a proper comparison -- `sct_deepseg_lesion` was trained on MS lesions
- [x] our model trained in a 2D fashion

EDIT: changed bullet points to check boxes

**Comment by naga-karthik** [comment]
I think this can now be closed, right? @valosekj

**Comment by valosekj** [comment]
Yes!
