### ISSUE TITLE
Include dataset commit into the log

### ISSUE THREAD

**Issue by valosekj** [ivadomed/model_seg_sci#61]
We can use the following SCT function:

https://github.com/spinalcordtoolbox/spinalcordtoolbox/blob/100087e7ca90f3ea91e6921b71ef443228828c1d/spinalcordtoolbox/utils/sys.py#L476

**Comment by jcohenadad** [comment]
Yes, it's fine to copy/paste whatever you need in a new standalone Python file, to not require SCT as a dependent tool

**Comment by naga-karthik** [comment]
Closing as fixed by #73
