### ISSUE TITLE
cannot import name 'predict_from_raw_data'

### ISSUE THREAD

**Issue by TayyssirB** [ivadomed/model_seg_sci#79]
File "C:\Users\tpc\Desktop\these\sciseg\model_seg_sci\packaging\run_inference.py", line 10, in <module>
    from nnunetv2.inference.predict_from_raw_data import predict_from_raw_data as predictor
ImportError: cannot import name 'predict_from_raw_data' from 'nnunetv2.inference.predict_from_raw_data'

**Comment by valosekj** [comment]
@TayyssirB thank you for reporting this!

Did you follow the [installation instructions](https://github.com/ivadomed/model_seg_sci/tree/main?tab=readme-ov-file#getting-started)? Specifically, did you run the following commands?

```console
conda create -n venv_nnunet python=3.9
conda activate venv_nnunet
pip install -r packaging/requirements.txt
```

**Comment by TayyssirB** [comment]
yes i did 
(venv_nnunet) C:\Users\tpc\Desktop\these\sciseg\model_seg_sci>pip install -r packaging/requirements.txt
Collecting numpy (from -r packaging/requirements.txt (line 1))
  Downloading numpy-1.26.4-cp39-cp39-win_amd64.whl.metadata (61 kB)
     ---------------------------------------- 61.0/61.0 kB 203.2 kB/s eta 0:00:00
Collecting nibabel (from -r packaging/requirements.txt (line 2)) ..... etc etc

**Comment by valosekj** [comment]
Okay, thank you for confirming this!

We recently added the model to the Spinal Cord Toolbox (SCT) v6.2. I updated the installation and usage instructions [here](https://github.com/ivadomed/model_seg_sci/blob/jv/update_README_SCTv62/README.md#how-to-use-the-model). Could you please follow them and let us know if it works?

**Comment by TayyssirB** [comment]
it works perfectly thanks
